### PR TITLE
Updated policy files

### PR DESCRIPTION
**Pull request by tmolitor-stud-tu**
I've added a new update script, too.

### CODE REVIEW

**Comment by csware** [comment]
Wouldn't it be good if we have a single file with the domain names and then automatically generate the two policy files?

**Comment by tmolitor-stud-tu** [comment]
Okay, this should be the last iteration of the update script for now, everything should be stable and usable now :)

**Comment by csware** [comment]
Your script changed a few `.DOMAIN.TLD` to just `DOMAIN.TLD` . I think this is fine, but a limitation.

**Comment by csware** [comment]
Some domains such as `bfdi.bund.de` are not reported as `dane-ony` when I execute the script. `dig MX bfdi.bund.de` reports that the `ad` flag is set.

**Comment by tmolitor-stud-tu** [comment]
what commandline arguments did you use exactly?
When I execute `scripts/update.py --log=DEBUG --no-mixed-lowest --min-security 
dane --force-dane bfdi.bund.de` I get a proper `bfdi.bund.de            dane-
only`.


Am Montag, 27. Mai 2024, 13:26:50 CEST schrieb Sven Strickroth:
> bfdi.bund.de

**Comment by csware** [comment]
> what commandline arguments did you use exactly? When I execute `scripts/update.py --log=DEBUG --no-mixed-lowest --min-security dane --force-dane bfdi.bund.de` I get a proper `bfdi.bund.de dane- only`. Am Montag, 27. Mai 2024, 13:26:50 CEST schrieb Sven Strickroth:

Doesn't matter, cf. a4a29870c8b5b440a3e2a026e6f58132d7304431

**Comment by tmolitor-stud-tu** [comment]
> Your script changed a few `.DOMAIN.TLD` to just `DOMAIN.TLD` . I think this is fine, but a limitation.

Yes, it uses the exact MX domain, if there is only one (for my server it's `mail.molitor-dietzel.de` for example, instead of `.molitor-dietzel.de`.

If the nexthop domain and the second level domain of the mailserver match, my script will output `nexthop:dot-nexthop` as match rule.
If the domains *don't* match, it will output the common suffix of all alt entries extracted from the cert and use the public suffix list to determine the minimal suffix to keep (and use `.domain` notation only if multiple alt names have a common suffix).

We could always add an additional `.suffix` entry if none was extracted, though. What do you think? Adding this won' be much work either.

**Comment by csware** [comment]
It's not about the `match` criteria, it's about the key on the left hand side, i.e., that a policy should be applied to all subdomains.

**Comment by tmolitor-stud-tu** [comment]
> It's not about the `match` criteria, it's about the key on the left hand side, i.e., that a policy should be applied to all subdomains (e.g., `.berlin.de secure match=something` would match for `a.berlin.de`, `b.berlin.de`, `berlin.de` etc..

oh sorry, I misunderstood you then.
Yes, adding an "and all subdomains"-entry would be a good idea to lock down things :)
I'll update my script.

**Comment by csware** [comment]
Domains starting with a dot should be handlet like the main domain without the dot prefix but inserted with the dot into policy file.

**Comment by csware** [comment]
`--min-security encrypt` does not work and will always generate a fingerprint entry.

**Comment by tmolitor-stud-tu** [comment]
> Domains starting with a dot should be handlet like the main domain without the dot prefix but inserted with the dot into policy file.

yes, I'll add that :)



> `--min-security encrypt` does not work and will always generate a fingerprint entry.

Strange, I'll debug and fix that.

**Pull request merged**
